// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'DefaultTableCell.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

DefaultTableCell _$DefaultTableCellFromJson(Map<String, dynamic> json) {
  return DefaultTableCell(
      json['Address'] as String,
      json['InstallMan'] as String,
      json['InstallDate'] as String,
      json['SaleMan'] as String,
      json['RealNodePath'] as String,
      json['note6'] as String,
      json['note6_color'] as String,
      json['MaintainTime'] as String,
      json['AssignMan'] as String,
      json['BossNodePath'] as String,
      json['OTIME'] as String,
      json['CustNo'] as String,
      json['note1'] as String,
      json['note1_color'] as String,
      json['CustClass'] as String,
      json['Name'] as String,
      json['isMarjor'] as String,
      json['RestartCount'] as String,
      json['RestartTime'] as String,
      json['U0_SNR'] as String,
      json['U1_SNR'] as String,
      json['U2_SNR'] as String,
      json['U3_SNR'] as String,
      json['U0_PWR'] as String,
      json['U1_PWR'] as String,
      json['U2_PWR'] as String,
      json['U3_PWR'] as String,
      json['DS0'] as String,
      json['DS1'] as String,
      json['DS2'] as String,
      json['DS3'] as String,
      json['DS4'] as String,
      json['DS5'] as String,
      json['DS6'] as String,
      json['DS7'] as String,
      json['DP0'] as String,
      json['DP1'] as String,
      json['DP2'] as String,
      json['DP3'] as String,
      json['DP4'] as String,
      json['DP5'] as String,
      json['DP6'] as String,
      json['DP7'] as String,
      json['Status'] as String,
      json['BB'] as String,
      json['note2'] as String,
      json['note2_color'] as String,
      json['note3'] as String,
      json['note3_color'] as String,
      json['note4'] as String,
      json['note4_color'] as String,
      json['note5'] as String,
      json['note5_color'] as String,
      json['DataTime2'] as String,
      json['USFLOW'] as String,
      json['DSFLOW'] as String,
      json['Response'] as String,
      json['PacketLoss'] as String,
      json['ReportLog'] as String,
      json['U0C'] as String,
      json['U0U'] as String,
      json['U1C'] as String,
      json['U1U'] as String,
      json['U2C'] as String,
      json['U2U'] as String,
      json['U3C'] as String,
      json['U3U'] as String);
}

Map<String, dynamic> _$DefaultTableCellToJson(DefaultTableCell instance) =>
    <String, dynamic>{
      'Address': instance.Address,
      'InstallMan': instance.InstallMan,
      'InstallDate': instance.InstallDate,
      'SaleMan': instance.SaleMan,
      'RealNodePath': instance.RealNodePath,
      'note6': instance.note6,
      'note6_color': instance.note6_color,
      'MaintainTime': instance.MaintainTime,
      'AssignMan': instance.AssignMan,
      'BossNodePath': instance.BossNodePath,
      'OTIME': instance.OTIME,
      'CustNo': instance.CustNo,
      'note1': instance.note1,
      'note1_color': instance.note1_color,
      'CustClass': instance.CustClass,
      'Name': instance.Name,
      'isMarjor': instance.isMarjor,
      'RestartCount': instance.RestartCount,
      'RestartTime': instance.RestartTime,
      'U0_SNR': instance.U0_SNR,
      'U1_SNR': instance.U1_SNR,
      'U2_SNR': instance.U2_SNR,
      'U3_SNR': instance.U3_SNR,
      'U0_PWR': instance.U0_PWR,
      'U1_PWR': instance.U1_PWR,
      'U2_PWR': instance.U2_PWR,
      'U3_PWR': instance.U3_PWR,
      'DS0': instance.DS0,
      'DS1': instance.DS1,
      'DS2': instance.DS2,
      'DS3': instance.DS3,
      'DS4': instance.DS4,
      'DS5': instance.DS5,
      'DS6': instance.DS6,
      'DS7': instance.DS7,
      'DP0': instance.DP0,
      'DP1': instance.DP1,
      'DP2': instance.DP2,
      'DP3': instance.DP3,
      'DP4': instance.DP4,
      'DP5': instance.DP5,
      'DP6': instance.DP6,
      'DP7': instance.DP7,
      'Status': instance.Status,
      'BB': instance.BB,
      'note2': instance.note2,
      'note2_color': instance.note2_color,
      'note3': instance.note3,
      'note3_color': instance.note3_color,
      'note4': instance.note4,
      'note4_color': instance.note4_color,
      'note5': instance.note5,
      'note5_color': instance.note5_color,
      'DataTime2': instance.DataTime2,
      'USFLOW': instance.USFLOW,
      'DSFLOW': instance.DSFLOW,
      'Response': instance.Response,
      'PacketLoss': instance.PacketLoss,
      'ReportLog': instance.ReportLog,
      'U0C': instance.U0C,
      'U0U': instance.U0U,
      'U1C': instance.U1C,
      'U1U': instance.U1U,
      'U2C': instance.U2C,
      'U2U': instance.U2U,
      'U3C': instance.U3C,
      'U3U': instance.U3U
    };
