// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'SmallPingTableCell.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

SmallPingTableCell _$SmallPingTableCellFromJson(Map<String, dynamic> json) {
  return SmallPingTableCell(
      json['CMTS'] as String,
      json['CIF'] as String,
      json['NODE'] as String,
      json['CustCode'] as String,
      json['COUNT'] as Map<String,dynamic>,
      json['ONLINETIME'] as String,
      json['CMSWVER'] as String,
      json['CustName'] as String,
      json['BB'] as String,
      json['BuildingName'] as String,
      json['DS0'] as String,
      json['DS1'] as String,
      json['DS2'] as String,
      json['DS3'] as String,
      json['DS4'] as String,
      json['DS5'] as String,
      json['DS6'] as String,
      json['DS7'] as String,
      json['DP0'] as String,
      json['DP1'] as String,
      json['DP2'] as String,
      json['DP3'] as String,
      json['DP4'] as String,
      json['DP5'] as String,
      json['DP6'] as String,
      json['DP7'] as String,
      json['STATUS'] as String,
      json['PINGTIME'] as String,
      json['note1'] as String,
      json['note1_color'] as String,
      json['note2'] as String,
      json['note2_color'] as String,
      json['note3'] as String,
      json['note3_color'] as String,
      json['note4'] as String,
      json['note4_color'] as String,
      json['note5'] as String,
      json['note5_color'] as String,
      json['USFLOW'] as String,
      json['DSFLOW'] as String,
      json['Response'] as String,
      json['PacketLoss'] as String,
      json['CodeWord'] as Map<String,dynamic>,
          
      json['SNR'] as Map<String,dynamic>,
    );
}

Map<String, dynamic> _$SmallPingTableCellToJson(SmallPingTableCell instance) =>
    <String, dynamic>{
      'CMTS': instance.CMTS,
      'CIF': instance.CIF,
      'NODE': instance.NODE,
      'CustCode': instance.CustCode,
      'COUNT': instance.COUNT,
      'ONLINETIME': instance.ONLINETIME,
      'CMSWVER': instance.CMSWVER,
      'CustName': instance.CustName,
      'BB': instance.BB,
      'BuildingName': instance.BuildingName,
      'DS0': instance.DS0,
      'DS1': instance.DS1,
      'DS2': instance.DS2,
      'DS3': instance.DS3,
      'DS4': instance.DS4,
      'DS5': instance.DS5,
      'DS6': instance.DS6,
      'DS7': instance.DS7,
      'DP0': instance.DP0,
      'DP1': instance.DP1,
      'DP2': instance.DP2,
      'DP3': instance.DP3,
      'DP4': instance.DP4,
      'DP5': instance.DP5,
      'DP6': instance.DP6,
      'DP7': instance.DP7,
      'STATUS': instance.STATUS,
      'PINGTIME': instance.PINGTIME,
      'note1': instance.note1,
      'note1_color': instance.note1_color,
      'note2': instance.note2,
      'note2_color': instance.note2_color,
      'note3': instance.note3,
      'note3_color': instance.note3_color,
      'note4': instance.note4,
      'note4_color': instance.note4_color,
      'note5': instance.note5,
      'note5_color': instance.note5_color,
      'USFLOW': instance.USFLOW,
      'DSFLOW': instance.DSFLOW,
      'Response': instance.Response,
      'PacketLoss': instance.PacketLoss,
      'SNR': instance.SNR,
      'CodeWord': instance.CodeWord
    };
